### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by funkytaco** [mikehenrty/thin-pdo-wrapper#9]
I see a couple outstanding issues from 2013, and was looking for a lightweight PDO wrapper. I was wondering if this project is maintained.

**Comment by mikehenrty** [comment]
I'll fix bugs as you report them. I think the issues you mentioned (#5 and #6) are more like feature requests, which I will gladly accept PR's for, but probably won't address myself unless I think it will be useful to a lot of people.

**Comment by mikehenrty** [comment]
Out of curiosity, what kind of project are you using this for @funkytaco? Are you planning to use the composer package?

**Comment by funkytaco** [comment]
I'm doing this as an excercise for a "No Framework" for PHP project. Yes, it'd be via composer. See https://github.com/funkytaco/php-seed-bootstrap.

I'm not looking to replace PDO as it is solid now. My project could just work with PDO passthrough, but, I want to just setup a class that lets the database abstraction layer to let you switch out what you use (i.e. switch out thin-pdo-wrapper for something else without too much work). 

Try it out if you want. I tried to keep the project clean, but I need criticism as I'm not sure what else to implement or change.

**Comment by mikehenrty** [comment]
Nice, I like the No Framework approach very much :+1: That said, I don't think I can give you much useful input into your experiment since I haven't kept up with the latest PHP techniques. The code looks reasonable to me, and I like the idea of swapping DB abstraction layers.

If you do use this project and find any bugs, don't hesitate to file. In the meantime I'll close this issue.
